server:
  port: ${APP_PORT}
spring:
  datasource:
    url: ${DATABASE}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat,wall        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 1
      min-idle: 1
      max-active: 30
      max-wait: 10000
      time-between-eviction-runs-millis: 20000        # 配置一个连接在池中生存的时间，单位是毫秒
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 5000
          merge-sql: true
      max-pool-prepared-statement-per-connection-size: 20
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    mode: HTML5
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.docker.test.demo.domain.model
  configuration:
    autoRuntimeDialect: true
